name: styleclub
version: 3.0.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'
  
dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_fadein: 2.0.0
  velocity_x: 3.5.1
  
  introduction_screen: ^3.0.1
  flutter_image_slideshow: 0.1.2
  persistent_bottom_nav_bar: 4.0.2
  flutter_svg: 1.1.3
  intl: 0.17.0
  graphql_flutter: ^5.0.0
  linear_progress_bar: ^1.1.0
  flutter: 
    sdk: flutter
  country_list_pick: ^1.0.1+6
  tuple: ^2.0.0
  intl_phone_field: ^3.1.0
  country_pickers: ^2.0.0
  sizer: ^2.0.15
  carousel_indicator: ^1.0.6
  glassmorphism: ^3.0.0
  google_fonts: ^3.0.1
  firebase_auth: ^4.2.6
  google_sign_in: ^5.4.4
  firebase_core: ^2.5.0
  http: ^0.13.5
  simple_s3: ^0.3.2
  file_picker: ^5.2.7
  toast: ^0.3.0
  direct_select: ^2.0.0
  flutter_screenutil: ^5.6.0
  image_picker: ^0.8.6
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.10
  razorpay_flutter: ^1.3.4
  pusher_beams: ^1.1.1
  cached_network_image: ^3.2.3
  flutter_staggered_grid_view: ^0.4.0
  shimmer: ^2.0.0
  pull_to_refresh: ^2.0.0
  google_maps_flutter: ^2.2.5

  jwt_decoder: ^2.0.1
  qr_code_scanner: ^1.0.1
  expandable: ^5.0.1
  slide_to_act: ^2.0.1
  faker: ^2.1.0
  flutter_picker: ^2.0.5
  qr_flutter: ^4.0.0
  share_plus: ^6.3.1
  
 
 
 
dependency_overrides:
  
dev_dependencies: 
  flutter_lints: ^1.0.0
  
  build_runner: any
 
  flutter_test: 
    sdk: flutter

flutter: 
  fonts: 
    - family: ave
      fonts: 
        - asset: assets/fonts/avenirbook.otf
    - family: ave_black
      fonts: 
        - asset: assets/fonts/Avenir Black.ttf
    - family: poppins
      fonts: 
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: dmsans
      fonts: 
        - asset: assets/fonts/DMsans-Regular.ttf
    

  assets: 
    - assets/
  uses-material-design: true

