part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const BOOK = _Paths.BOOK;
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const WELCOME = _Paths.WELCOME;
  static const PHOTO_UPLOAD = _Paths.PHOTO_UPLOAD;
  static const SUCCESS_PAGE = _Paths.SUCCESS_PAGE;
  static const SPLASHES = _Paths.SPLASHES;
  static const ELEVATE_PAGE = _Paths.ELEVATE_PAGE;
  static const SIGNUP_PAGE = _Paths.SIGNUP_PAGE;
  static const LOGIN_PAGE = _Paths.LOGIN_PAGE;
  static const LOGIN_PAGE_PASS = _Paths.LOGIN_PAGE_PASS;
  static const TANDC = _Paths.TANDC;
  static const MAIN_PAGE = _Paths.MAIN_PAGE;
  static const HOME_PAGE = _Paths.HOME_PAGE;
  static const INFLUENCE_PAGE = _Paths.INFLUENCE_PAGE;
  static const DEALS_PAGE = _Paths.DEALS_PAGE;
  static const CHAT_PAGE = _Paths.CHAT_PAGE;
  static const OTPVERIFY = _Paths.OTPVERIFY;
  static const CREATE_DIGITAL_IDENTITY = _Paths.CREATE_DIGITAL_IDENTITY;
  static const SEE_PROFILE = _Paths.SEE_PROFILE;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const EDIT_SOCIAL_MEDIA = _Paths.EDIT_SOCIAL_MEDIA;
  static const EDIT_ACCOUNT_SETTINGS = _Paths.EDIT_ACCOUNT_SETTINGS;
  static const SCAN_CARD = _Paths.SCAN_CARD;
  static const ADD_PHOTO = _Paths.ADD_PHOTO;
  static const SETTINGS = _Paths.SETTINGS;
  static const CONNECTED = _Paths.CONNECTED;
  static const SHARE = _Paths.SHARE;
  static const PRIVILEGE_PAGE = _Paths.PRIVILEGE_PAGE;
  static const GROOMING_PAGE = _Paths.GROOMING_PAGE;
  static const HARISTYLE_DETAIL_PAGE = _Paths.HARISTYLE_DETAIL_PAGE;
  static const BARBER_DETAIL_PAGE = _Paths.BARBER_DETAIL_PAGE;
  static const STYLING_PAGE = _Paths.STYLING_PAGE;
  static const SHOP_PAGE = _Paths.SHOP_PAGE;
  static const SHOP_DETAILS_PAGE = _Paths.SHOP_DETAILS_PAGE;
  static const CART_PAGE = _Paths.CART_PAGE;
  static const CONGRATS = _Paths.CONGRATS;
  static const PAYMENT1 = _Paths.PAYMENT1;
  static const NOTI = _Paths.NOTI;
  static const HEIGHT_PAGE = _Paths.HEIGHT_PAGE;
  static const RESET_PAGE = _Paths.RESET_PAGE;
}

abstract class _Paths {
  _Paths._();
  static const BOOK = "/book";
  static const HOME = '/home';
  static const SPLASH = '/splash';
  static const ONBOARDING = '/onboarding';
  static const WELCOME = '/welcome';
  static const PHOTO_UPLOAD = '/photo-upload';
  static const SUCCESS_PAGE = '/success-page';
  static const SPLASHES = '/splashes';
  static const ELEVATE_PAGE = '/elevate-page';
  static const SIGNUP_PAGE = '/signup-page';
  static const LOGIN_PAGE = '/login-page';
  static const LOGIN_PAGE_PASS = '/login-page-pass';
  static const TANDC = '/tandc';
  static const CONGRATS = '/congrats';
  static const MAIN_PAGE = '/main-page';
  static const HOME_PAGE = '/home-page';
  static const INFLUENCE_PAGE = '/influence-page';
  static const DEALS_PAGE = '/deals-page';
  static const CHAT_PAGE = '/chat-page';
  static const OTPVERIFY = '/otpverify';
  static const CREATE_DIGITAL_IDENTITY = '/create-digital-identity';
  static const SEE_PROFILE = '/see-profile';
  static const EDIT_PROFILE = '/edit-profile';
  static const EDIT_SOCIAL_MEDIA = '/edit-social-media';
  static const EDIT_ACCOUNT_SETTINGS = '/edit-account-settings';
  static const SCAN_CARD = '/scan-card';
  static const ADD_PHOTO = '/add-photo';
  static const SETTINGS = '/settings';
  static const CONNECTED = '/connected';
  static const SHARE = '/share';
  static const NOTI = '/noti';
  static const PAYMENT1 = '/payment1';
  static const PRIVILEGE_PAGE = '/privilege-page';
  static const GROOMING_PAGE = '/grooming-page';
  static const HARISTYLE_DETAIL_PAGE = '/haristyle-detail-page';
  static const BARBER_DETAIL_PAGE = '/barber-detail-page';
  static const STYLING_PAGE = '/styling-page';
  static const SHOP_PAGE = '/shop-page';
  static const SHOP_DETAILS_PAGE = '/shop-details-page';
  static const CART_PAGE = '/cart-page';
  static const HEIGHT_PAGE = '/height-page';
  static const RESET_PAGE = '/reset-pass';
}
